
import { DeclarationCategory } from '@/types/declarations';

export const DECLARATION_CATEGORIES: DeclarationCategory[] = [
  {
    id: 'identity',
    title: 'Identity Declarations',
    source: 'Identity_Declarations.pdf',
    declarations: [
      "I am God's workmanship - Ephesians 2:10",
      "I am filled with His Spirit - Romans 8:11",
      "I am worthy - Isaiah 43:4",
      "I am enough - 2 Corinthians 12:9",
      "I am loved - Romans 8:11",
      "I am known by God - Psalm 139:13-14",
      "I have the mind of Christ - 1 Corinthians 2:16",
      "I am a glory carrier - John 17:22",
      "I am strong when I am weak - 2 Corinthians 12:10",
      "I am confident God is for me - Romans 8:31",
      "I am abounding in hope by the power of the Holy Spirit - Romans 15:13",
      "I am alive in Christ - Romans 6:4, Ephesians 2:4-5",
      "I am His bride - Isaiah 54:4",
      "I am full of peace - John 14:27",
      "I am blessed - Deuteronomy 28:2-13",
      "I am as bold as a lion - Proverbs 28:1",
      "I was created for good works, and I will walk in them - Ephesians 2:10",
      "I am seated in heavenly places - Ephesians 2:6",
      "I am created in His image - Genesis 1:27",
      "I am God's child - John 1:12",
      "I am Jesus' friend - John 15:15",
      "I am adopted into God's family - Romans 8:15",
      "I am completely forgiven - Colossians 2:13",
      "I am the head and not the tail - Deuteronomy 28:13",
      "I am healed by his wounds - 1 Peter 2:24",
      "I am a citizen of heaven - Ephesians 2:19"
    ]
  },
  {
    id: 'biblical',
    title: '100 Biblical Declarations',
    source: '100_Biblical_Declarations.pdf',
    declarations: [
      "As I live in God, my love grows more perfect. I can face Him with confidence on the day of judgment because I live like Jesus here in this world - 1 John 4:17",
      "I receive an abundance of grace and the gift of righteousness. I reign in life through Jesus Christ - Romans 5:17",
      "I look out not only for my own interests but also for the interests of others - Philippians 2:4",
      "I am kind and tenderhearted to others. I forgive them as God in Christ has forgiven me - Ephesians 4:32",
      "I can do all things through Christ who strengthens me - Philippians 4:13",
      "I ask God to set a guard over my mouth. He keeps watch over the door of my lips - Psalm 141:3",
      "I let the peace of Christ rule in my heart. As a member of one body, I am called to peace, and I am thankful - Colossians 3:15",
      "I walk in a manner worthy of the Lord, pleasing Him in all respects. I bear fruit in every good work, and I am increasing in the knowledge of God - Colossians 1:10",
      "I am being strengthened with all power according to His might. I have great endurance and patience - Colossians 1:11",
      "God has not given me a spirit of fear. He gives me power, love, and self-discipline - 2 Timothy 1:7",
      "God loads me daily with benefits. He is my salvation - Psalm 68:19",
      "I am God's servant, and He takes pleasure in my prosperity - Psalm 35:27",
      "I meditate on God's word day and night. I am successful and prosperous - Psalm 1:2-3, Joshua 1:8",
      "God makes all grace abound toward me so that I always have all sufficiency and an abundance for every good work - 2 Corinthians 9:8",
      "I honor the Lord with my wealth and the first fruits of all my produce. Then, my barns will be filled with plenty - Proverbs 3:9-10",
      "I bring the whole tithe into the storehouse. He opens the windows of heaven for me and pours out a blessing so great that I don't have enough room for it - Malachi 3:10",
      "I prosper in all things. I remain in health just as my soul prospers - 3 John 1:3",
      "God abundantly blesses my provision - Psalm 132:15",
      "I honor the Lord with my wealth and the first fruits of all my produce. Then, my barns will be filled with plenty - Proverbs 3:9-10",
      "I bring the whole tithe into the storehouse. He opens the windows of heaven for me and pours out a blessing so great that I don't have enough room for it - Malachi 3:10",
      "I prosper in all things. I remain in health just as my soul prospers - 3 John 1:3",
      "God abundantly blesses my provision - Psalm 132:15",
      "I give, and I receive. Good measure, pressed down, shaken together, running over, will it be put into my lap - Luke 6:38",
      "Jesus Christ is generous in grace. Though He was rich, yet for my sake he became poor, so that by His poverty He could make me rich - 2 Corinthians 8:9",
      "Christ redeemed me from the curse of the law by becoming a curse for me - Galatians 3:13",
      "I experience all blessings as I obey the Lord my God - Deuteronomy 28:2",
      "I am blessed in the city and blessed in the country - Deuteronomy 28:3",
      "I am blessed from the fruit of my body. I am blessed with today's equivalent of the produce of the ground, the increase of my herds, my cattle, and the offspring of my flock - Deuteronomy 28:4",
      "My kneading bowl and basket are blessed. It is the means by which I am tangibly blessed - Deuteronomy 28:5",
      "I am blessed when I come in and blessed when I go out - Deuteronomy 28:6",
      "The LORD causes my enemies who rise against me to be defeated before my face; they come out against me one way and flee before me seven ways - Deuteronomy 28:7",
      "The LORD commands His blessing on my storehouses and in all that I set my hand to do, and He blesses me in the land that He is giving me - Deuteronomy 28:8",
      "The Lord has established me as a holy person to Himself. I keep His commandments and walk in His ways - Deuteronomy 28:9",
      "All the people of the earth see that I am called by the name of the LORD - Deuteronomy 28:10",
      "The LORD grants me plenty of goods, in the fruit of my body, in the increase of my livestock, and in the produce of my ground - Deuteronomy 28:11",
      "The LORD opens to me His good treasure, the heavens to give the rain to my land in its season and to bless all the work of my hand - Deuteronomy 28:12",
      "I lend to many nations, but I will not borrow - Deuteronomy 28:12",
      "The Lord makes me the head and not the tail, above and not beneath - Deuteronomy 28:13",
      "I am my Father's child. I am always with Him and all that He has is mine - Luke 15:31",
      "God blesses me and surrounds me with favor as a shield - Psalm 5:12",
      "My ways please the LORD and He makes even my enemies to be at peace with me - Proverbs 16:7",
      "By God's doing I am in Christ Jesus. He became to me wisdom, righteousness, sanctification, and redemption - 1 Corinthians 1:30",
      "The God of hope fills me with all joy and peace in believing so that I abound in hope by the power of the Holy Spirit - Romans 15:13",
      "The Lord of peace is peace. In every way, He always gives me His peace - 2 Thessalonians 3:16",
      "I always rejoice and pray without ceasing. In everything, I give thanks for this is the will of God in Christ Jesus for me - 1 Thessalonians 5:16-18",
      "I am steadfast of mind. He keeps me in perfect peace because I trust in Him - Isaiah 26:3",
      "The joy of the LORD is my strength - Nehemiah 8:10",
      "I am confident of this very thing, that He who has begun a good work in me will complete it until the day of Jesus Christ - Philippians 1:6",
      "God works in me both to will and to do His good pleasure - Philippians 2:13",
      "I do all things without grumbling or complaining so that I will prove myself to be blameless and innocent - Philippians 2:14-15",
      "I hold fast to the word of life. In the day of Christ's return, I will have reason to glory because I did not run or labor in vain - Philippians 2:16",
      "I always rejoice in the Lord and my gentleness is known to all people - Philippians 4:4-5",
      "I am anxious for nothing, but in everything by prayer and supplication with thanksgiving I let my requests be made known to God - Philippians 4:6-7",
      "I choose to meditate on anything that has virtue or is praiseworthy. I think about things are true, noble, just, pure, lovely, and of good report - Philippians 4:8",
      "I press on, that I may lay hold of that which Christ Jesus has also laid hold of me - Philippians 3:12-14",
      "The Lord is my God! He is mighty to save. He rejoices over me with gladness and singing. I am quieted by His love - Zephaniah 3:17",
      "God instructs me and keeps me as the apple of His eye - Zechariah 2:8",
      "I am a crown of glory and a royal diadem in the hand of the LORD - Isaiah 62:3",
      "I am no longer called Forsaken or Desolate. My new names are Hepbzibah (my delight is in her) and Beulah (married). He delights in me, and I am married to Him - Isaiah 62:4",
      "God rejoices over me as a bridegroom rejoices over his bride - Isaiah 62:5",
      "The LORD has chosen me for Himself as His special treasure - Psalm 135:4",
      "I speak God's word and hearing the word increases my faith - Romans 10:17",
      "I declare God's word about who I am, what I have, and what I can do in Christ Jesus who gives me strength - Job 22:8, Isaiah 60:1",
      "I speak God's word, and His angels do the voice of His word - Psalm 103:20",
      "I speak God's word, and it does not return to Him void. His word accomplishes what He pleases, and it prospers in the thing for which He sends it - Isaiah 55:11",
      "I persist in speaking God's word until it accomplishes its purpose. It is like fire. It is like a hammer that shatters a rock - Jeremiah 23:29",
      "The Lord has given me the tongue of the disciples. I know how to speak a word in due season to those who are weary - Isaiah 50:4",
      "The Lord God awakens me every morning to fellowship with Him, and He opens my ears to hear as the learned - Isaiah 50:4",
      "I speak pleasant words that are sweet to the soul and healing to the bones. I am wise and I bring healing - Proverbs 16:24, Proverbs 12:18",
      "I have a wholesome tongue which is a tree of life to myself and others - Proverbs 15:4, Proverbs 11:30, Proverbs 18:21",
      "I speak words of life. I am satisfied with the good by the fruit produced by my words - Proverbs 12:14, Proverbs 18:20",
      "As I speak God's word, He sends it to heal and deliver me from my destruction - Psalm 107:20",
      "God forgives all my iniquities and heals all my diseases - Psalm 103:3",
      "God redeems my life from the pit. He crowns me with lovingkindness and compassion - Psalm 103:4",
      "God satisfies my mouth with good things and renews my youth like the eagles' - Psalm 103:5",
      "Christ bore my sins in His own body on the cross and I am healed by His stripes - 1 Peter 2:24",
      "I am blessed with every spiritual blessing in the heavenly places in Christ - Ephesians 1:3",
      "I am chosen in Christ before the foundation of the world that I may be holy and blameless before the Father - Ephesians 1:4",
      "I am predestined to adoption as a son or daughter by the Father through Jesus Christ according to the good pleasure of His will - Ephesians 1:5",
      "The Father has accepted me in the beloved - Ephesians 1:6",
      "I have redemption through Jesus Christ's blood and the forgiveness of sins - Ephesians 1:7, Colossians 1:14",
      "I have obtained an inheritance in Christ - Ephesians 1:11",
      "I am sealed with the Holy Spirit who is the guarantee of my inheritance - Ephesians 1:13-14",
      "God raised me up in heavenly places to sit with Him in Jesus Christ - Ephesians 2:6",
      "I am saved by grace through faith. I am not saved by my own works - Ephesians 2:8-9",
      "I am God's masterpiece. He created me anew in Christ Jesus, so I can do the good things He planned for me long ago - Ephesians 2:10",
      "I have been brought to Father by the blood of Christ - Ephesians 2:13",
      "For He Himself is my peace. He made the Gentiles and the Jews into one by breaking down the barrier of the dividing wall - Ephesians 2:14",
      "I have access by one Spirit to the Father through Christ Jesus - Ephesians 2:18",
      "I am strengthened with might through His Spirit in the inner man according to the riches of His glory - Ephesians 3:16",
      "Christ dwells in my heart by faith. I am rooted and grounded in love - Ephesians 3:17",
      "God does exceedingly abundantly above all that I could ask or think according to His power that works in me - Ephesians 3:20",
      "God gives me the victory through Jesus Christ my Lord - 1 Corinthians 15:57",
      "I thank God! He always leads me triumphantly by the Messiah and through me spreads everywhere the fragrance of knowing Him - 2 Corinthians 2:14",
      "I have the mind of Christ - 1 Corinthians 2:16",
      "He made Christ who knew no sin to be sin for me that I might become the righteousness of God in Him - 2 Corinthians 5:21",
      "I am in Christ Jesus and therefore I am a new creation. Old things have passed away and all things have become new - 2 Corinthians 5:17",
      "If I sin, I have an advocate with the Father, Jesus Christ the righteous - 1 John 2:1",
      "All of God's promises are yes and amen for me because I am in Christ - 2 Corinthians 1:20",
      "I am qualified in Christ to be a partaker of the inheritance of the saints - Colossians 1:12",
      "God my Father has delivered me from the power of darkness and transferred me into the kingdom of His beloved Son - Colossians 1:13"
    ]
  },
  {
    id: 'leadership',
    title: 'Leadership Beliefs',
    source: '25_Leadership_Beliefs_to_Declare.pdf',
    declarations: [
      "Adaptability – I will thrive no matter what happens. (Philippians 4:11-13)",
      "Hope – I believe the future will be better than the present and I have the power to help make it so. (Romans 15:13; Jeremiah 29:4-11)",
      "Faith – I am thankful that God's promises and my past prayers are working in my life, my family's lives, my circumstances, and my nation. (Hebrews 11:1)",
      "Forgiveness – My intentional forgiveness creates well-being for others and for me. (Luke 23:34; Acts 7:60-8:1)",
      "Long-Term Thinking – My beliefs and choices are leaving a positive legacy for generations to come. (Hebrews 11:20)",
      "Joy and Laughter – I have strength and longevity because I consistently activate joy and laughter in my life. (Nehemiah 8:10; Proverbs 17:22)",
      "Solutions – In every situation I face, I have many options, solutions, and divine ideas. There is always a solution. (1 Corinthians 10:13; James 1:5)",
      "Encouraging Others – I radically encourage others daily. (Hebrews 10:24-25; Hebrews 3:13)",
      "Soul Prosperity – My response to something is almost always more important than the something. (3 John 2)",
      "Bottom-Lining – Even if the worst happens, I will be okay. (Daniel 3:16-18)",
      "Training Focus – My current challenges and frustrations are my training ground for the greater influence I will have in the future. (James 1:2-5; Romans 5:3-4; Psalm 119:71)",
      "Peace – Peace is one of my strongest weapons in prayer. (Philippians 4:6-7; Romans 16:20)",
      "Follow Through and Integrity – I make commitments with forethought, and I follow through on what I say I will do. (Matthew 5:37; Psalm 15:4b)",
      "Imagination – I use my imagination to activate my faith. (2 Corinthians 4:18)",
      "Identity – I am not who my past says I am; I am who God says I am. (2 Corinthians 5:17; Hebrews 10:14)",
      "Spiritual Laws – I honor God's spiritual laws therefore I increase in favor, finance, health, and happiness. (Joshua 1:8; Psalm 1:2-3)",
      "Forward Movement – My forward movement in life causes Red Seas to part. (Exodus 14:15-21; Philippians 3:13)",
      "Courage – I am brave and run at my Goliaths. (1 Samuel 17:48)",
      "Authenticity – My authenticity connects my heart to people and gives hope to them. (Philippians 3:12; 1 Peter 5:5-6)",
      "Unique Purpose – I understand my assignment and giftings, and I know what God's called me to do and not to do. (Romans 12:4-8; 1 Peter 4:10-11)",
      "Decision Making – I am a great decision maker and attach faith to every decision I make. (Romans 14:5; James 1:5)",
      "Being Loved by God – I am unconditionally loved by God and worthy to receive love and blessings today. (1 John 4:19; Luke 15:20)",
      "Valuing Process – I don't wait for perfection to celebrate myself and be joyful. (Philippians 3:12-14)",
      "Beliefs About Others – I see people according to their potential, not according to their past. (2 Corinthians 5:16; Judges 6:12)",
      "Staying Relational – I will not withdraw my heart from people who disappoint me or that I hear negative information about. (1 Corinthians 13:4-7; 1 Timothy 5:19)"
    ]
  },
  {
    id: 'spirit',
    title: 'Spirit Awareness',
    source: '65_Spirit_Awareness_Declarations.pdf',
    declarations: [
      "I powerfully influence my surroundings",
      "I am abundantly blessed in my finances",
      "I know who I am in God and live accordingly",
      "I am empowered to change the world",
      "I am confident and happy with who I am",
      "I expect to experience the supernatural",
      "I prosper in all my relationships",
      "I am in inner unity with the beliefs of Jesus",
      "God passionately loves me",
      "I release peace, joy, and love to others",
      "My spirit is always aware of the unseen realm",
      "I have legal access in heavenly places",
      "I celebrate my progress",
      "People are drawn to me",
      "God is my perfect Father",
      "I trust what my spirit sees and senses",
      "I am aware of my spiritual senses",
      "My Dad's God",
      "My thought life is deeply connected to who I am in God",
      "It is natural for me to believe like Jesus",
      "God's goodness is my anchor in the storm",
      "My spirit has authority over my mind",
      "I carry the substance of favor",
      "I easily receive blessings",
      "I am a powerful person in speech and action",
      "I create strongholds of blessing wherever I go",
      "I receive constant nourishment to my body, soul, and spirit",
      "I am tremendously powerful because of the influence of the Holy Spirit",
      "The light of God within me destroys the works of the enemy",
      "My spirit imparts wisdom and knowledge to others",
      "Failure does not prevent me from receiving God's love",
      "I have been designed to flow in the supernatural",
      "I am worthy to see and experience the Kingdom of God",
      "I filter what I see, hear, and believe through the promises of God",
      "God is faithful to heal relationships in my life",
      "The talents God gave me bring energy and fulfillment to my life",
      "My thoughts, emotions, and words are in unity",
      "My unconscious beliefs are in unity with my speech",
      "My mind, will, and emotions are transformed by God's word",
      "My thoughts and attitudes carry a force in the unseen realm that affects my everyday life",
      "I intentionally build healthy strongholds in my mind and emotions",
      "I replace negative thought patterns with hope and truth",
      "I joyfully anticipate what God can do today",
      "My imagination is the soil for the seed of God's word",
      "I see my future through the lens of hope",
      "I build altars in my mind to God's faithfulness",
      "My identity comes from my Creator",
      "I always have a solution",
      "I have faith in the unseen realm",
      "Light is more powerful than darkness",
      "My life is worship",
      "I influence the atmosphere with God's presence",
      "I live a resurrected life",
      "I reveal the Holy Spirit through the things I enjoy",
      "I am supernatural therefore I am not limited to the natural realm",
      "I am connected to God in my worship",
      "God is always speaking to me",
      "The Word of God transforms my life",
      "I recognize and understand the Kingdom realm",
      "God protects me and my family",
      "My biblical optimism leads to breakthrough",
      "God supplies all my needs according to His riches in glory (Philippians 4:19)",
      "Increased revelation brings increase",
      "I quickly recognize lies and replace them with truth",
      "There's always hope for every situation"
    ]
  },
  {
    id: 'victorious',
    title: 'Victorious Mindsets',
    source: '50_Victorious_Mindsets_Declarations.pdf',
    declarations: [
      "I think thoughts of victory, not defeat",
      "I focus on solutions, not problems",
      "I see opportunities where others see obstacles",
      "I choose faith over fear in every situation",
      "I cultivate gratitude daily",
      "I expect God's goodness in my life",
      "I embrace change as a pathway to growth",
      "I reject negative thinking and embrace truth",
      "I am resilient in the face of challenges",
      "My mind is renewed by God's Word daily",
      "The Truth Will Make Me Free",
      "I Do Small Things in A Great Way",
      "Having Done All I Know to Do, I Stand",
      "I Am Anointed",
      "I Am Called of God",
      "My Prayers Are Powerful and Effective",
      "My Soul Is Prospering",
      "I Am Going Forward in Life",
      "I Run at My Goliath's",
      "If This Doesn't Work Out, Something Better Is Coming",
      "I Live to Plant into The Future",
      "I Have Healthy Long-Term Relationships",
      "I Encounter God by Faith",
      "I Am Repenting to Glistening Hope",
      "There Is a Way",
      "I Love Life",
      "I Don't Have to Be Perfect",
      "I Have a Great Work to Do",
      "God's Kindness Leads to Repentance",
      "I Can Adapt Well to Diverse Situations and People",
      "I Do Everything in Faith",
      "I Apply Great Faith to Everything I Do",
      "Today's Events Equip Me for My Future",
      "I Am Part of God's Genealogy For Revival",
      "My Past Does Not Determine My Future",
      "My Gifts Will Make Room for Me",
      "I Thrive Even If It's Not A \"Normal Week,\" Because I Realize There Are Few \"Normal Weeks.\"",
      "I Have Grace to Make Rock Decisions, Not Sandy Ones",
      "It Will Get Easier",
      "I Am Free from Fear",
      "When I Receive Impartation, I Am Radically Impacted",
      "I Am Full of Gratitude",
      "My Mind Is Being Renewed by The Word Of God",
      "I Cannot Fail",
      "I See Failures as Growth Opportunities, and I Am Set Up for Future Success",
      "I Do More Than Expected",
      "I Rejoice When Others are Blessed",
      "I Take the High Road",
      "I Lay My Life Down for Others",
      "I Put Things in My Path to Bump into That Contribute To My Personal Growth",
      "I Am Not Afraid of Missing Out",
      "Problems Are Opportunities",
      "I Welcome Resistance",
      "I Enthusiastically Serve Leaders",
      "I Am Ignited by a Burning Vision",
      "Light is More Powerful Than Darkness",
      "I Will Stay Hungry for God",
      "I Am First a Worshiper",
      "I Restrict My Behavior Because I Love Others",
      "It's Working"
    ]
  },
  {
    id: 'unseen',
    title: 'Living From the Unseen',
    source: 'Living_From_the_Unseen_Declarations.pdf',
    declarations: [
      "I live by faith, not by sight",
      "I am anchored in eternal realities",
      "I perceive what is invisible to natural eyes",
      "I am supernaturally sustained",
      "I access heavenly wisdom for earthly situations",
      "I carry the atmosphere of heaven",
      "I see from God's perspective",
      "I recognize divine appointments",
      "I tap into supernatural resources",
      "I live from a place of rest and peace"
    ]
  }
];
